name: quantum_protein_design
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - scipy
  - pip
  - pip:
      - pennylane
      - qiskit
      - qiskit-aer
      - qiskit-algorithms
      - dimod
      - dwave-neal
