name: protein_seq_quantum_CPU
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0=h313beb8_0
  - blas=1.0=openblas
  - brotli-python=1.0.9=py311h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - contourpy=1.3.1=py311h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.1=h313beb8_0
  - fontconfig=2.14.1=h6402c1e_3
  - fonttools=4.55.3=py311h80987f9_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.21.0=hbdbcc25_2
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - jpeg=9f=h2f69dba_0
  - kiwisolver=1.4.8=py311h313beb8_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libavif=1.1.1=h80987f9_0
  - libcxx=20.1.8=h8869778_0
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libiconv=1.16=h80987f9_3
  - libopenblas=0.3.29=hea593b9_0
  - libpng=1.6.39=h80987f9_0
  - libtiff=4.7.0=h91aec0a_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.10.6=py311hca03da5_0
  - matplotlib-base=3.10.6=py311h066045a_0
  - ncurses=6.5=hee39554_0
  - numpy=2.3.3=py311hc95ac1c_0
  - numpy-base=2.3.3=py311h8087a70_0
  - openjpeg=2.5.2=hba36e21_1
  - openssl=3.0.17=h4ee41c1_0
  - packaging=25.0=py311hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pillow=11.3.0=py311h6dd570d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - pyparsing=3.2.0=py311hca03da5_0
  - python=3.11.13=h19e8193_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - readline=8.3=h0b18652_0
  - setuptools=72.1.0=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - unicodedata2=15.1.0=py311h80987f9_1
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.6=hfb09047_0
  - pip:
      - appdirs==1.4.4
      - astunparse==1.6.3
      - autograd==1.8.0
      - autoray==0.8.2
      - cachetools==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - diastatic-malt==2.15.2
      - dill==0.4.0
      - dimod==0.12.21
      - dwave-neal==0.6.0
      - dwave-samplers==1.7.0
      - gast==0.6.0
      - idna==3.10
      - jax==0.9.0.1
      - jaxlib==0.9.0.1
      - joblib==1.5.2
      - kagglehub==0.3.13
      - llvmlite==0.45.1
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - networkx==3.5
      - numba==0.62.1
      - opt-einsum==3.4.0
      - ordered-set==4.1.0
      - pandas==2.3.3
      - pennylane==0.44.0
      - pennylane-lightning==0.44.0
      - psutil==7.1.0
      - pylatex==1.4.2
      - pylatexenc==2.10
      - pytz==2025.2
      - pyyaml==6.0.3
      - qiskit==1.4.5
      - qiskit-aer==0.17.2
      - qiskit-algorithms==0.4.0
      - qiskit-machine-learning==0.8.4
      - requests==2.32.5
      - rustworkx==0.17.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - scipy-openblas32==0.3.30.0.2
      - seaborn==0.13.2
      - stevedore==5.5.0
      - symengine==0.13.0
      - sympy==1.14.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /opt/anaconda3/envs/quantum_protein_design
