
name: protein_seq_quantum_GPU
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - alsa-lib=1.2.15.3=hb03c661_0
  - binutils_impl_linux-64=2.45.1=default_hfdba357_101
  - binutils_linux-64=2.45.1=default_h4852527_101
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cuda-cccl_linux-64=13.1.115=0
  - cuda-command-line-tools=13.1.1=0
  - cuda-compiler=13.1.1=ha63b06e_0
  - cuda-crt-dev_linux-64=13.1.115=0
  - cuda-crt-tools=13.1.115=0
  - cuda-ctadvisor=13.1.115=h4f1e1d6_1
  - cuda-cudart=13.1.80=h6205011_0
  - cuda-cudart-dev=13.1.80=h3b4bcfc_0
  - cuda-cudart-dev_linux-64=13.1.80=hbe36340_0
  - cuda-cudart-static=13.1.80=h3b4bcfc_0
  - cuda-cudart-static_linux-64=13.1.80=hbe36340_0
  - cuda-cudart_linux-64=13.1.80=h61a3acf_0
  - cuda-cuobjdump=13.1.115=he32a221_0
  - cuda-cupti=13.1.115=h4f1e1d6_0
  - cuda-cupti-dev=13.1.115=he32a221_0
  - cuda-cuxxfilt=13.1.115=he32a221_0
  - cuda-driver-dev=13.1.80=h3b4bcfc_0
  - cuda-driver-dev_linux-64=13.1.80=hbe36340_0
  - cuda-gdb=13.1.115=h4f1e1d6_0
  - cuda-libraries=13.1.1=0
  - cuda-libraries-dev=13.1.1=0
  - cuda-nsight=13.1.115=hf678805_0
  - cuda-nvcc=13.1.115=h4e12aa9_0
  - cuda-nvcc-dev_linux-64=13.1.115=0
  - cuda-nvcc-impl=13.1.115=h74be60c_0
  - cuda-nvcc-tools=13.1.115=h4f1e1d6_0
  - cuda-nvcc_linux-64=13.1.115=h292b653_0
  - cuda-nvdisasm=13.1.115=he32a221_0
  - cuda-nvml-dev=13.1.115=he32a221_0
  - cuda-nvprune=13.1.115=he32a221_0
  - cuda-nvrtc=13.1.115=he32a221_0
  - cuda-nvrtc-dev=13.1.115=he32a221_0
  - cuda-nvtx=13.1.115=h4f1e1d6_0
  - cuda-nvvm-dev_linux-64=13.1.115=0
  - cuda-nvvm-impl=13.1.115=h09b770d_0
  - cuda-nvvm-tools=13.1.115=h09b770d_0
  - cuda-opencl=13.1.115=h4f1e1d6_0
  - cuda-opencl-dev=13.1.115=h4f1e1d6_0
  - cuda-profiler-api=13.1.115=hf678805_0
  - cuda-sanitizer-api=13.1.118=hc1e0326_0
  - cuda-tileiras=13.1.80=h4f1e1d6_1
  - cuda-toolkit=13.1.1=ha63b06e_0
  - cuda-tools=13.1.1=0
  - cuda-version=13.1=hd92462c_3
  - cuda-visual-tools=13.1.1=0
  - dbus=1.16.2=h24cb091_1
  - fontconfig=2.15.0=h7e30c49_1
  - freetype=2.14.1=ha770c72_0
  - gcc_impl_linux-64=15.2.0=h56f5909_17
  - gcc_linux-64=15.2.0=h862fb80_21
  - gds-tools=1.16.1.26=h2e6a4e3_0
  - gmp=6.3.0=hac33072_2
  - gxx_impl_linux-64=15.2.0=hda75c37_17
  - gxx_linux-64=15.2.0=h59c6875_21
  - kernel-headers_linux-64=5.14.0=h3108a97_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libcublas=13.2.1.1=h0bdde2c_0
  - libcublas-dev=13.2.1.1=h0bdde2c_0
  - libcufft=12.1.0.78=h6fb6d45_0
  - libcufft-dev=12.1.0.78=h6fb6d45_0
  - libcufile=1.16.1.26=h3b4bcfc_0
  - libcufile-dev=1.16.1.26=h2e6a4e3_0
  - libcurand=10.4.1.81=h1b6c897_0
  - libcurand-dev=10.4.1.81=h1b6c897_0
  - libcusolver=12.0.9.81=hfcec1d2_0
  - libcusolver-dev=12.0.9.81=hfcec1d2_0
  - libcusparse=12.7.3.1=h693dda1_0
  - libcusparse-dev=12.7.3.1=h693dda1_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-devel_linux-64=15.2.0=hcc6f6b0_117
  - libgcc-ng=15.2.0=h69a702a_17
  - libglib=2.86.3=h6548e54_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_17
  - libiconv=1.18=h3b78370_2
  - liblzma=5.8.2=hb03c661_0
  - libnpp=13.0.3.3=hcc83568_0
  - libnpp-dev=13.0.3.3=hcc83568_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=13.1.115=he32a221_0
  - libnvfatbin-dev=13.1.115=he32a221_0
  - libnvjitlink=13.1.115=he32a221_0
  - libnvjitlink-dev=13.1.115=he32a221_0
  - libnvjpeg=13.0.3.75=h06761be_0
  - libnvjpeg-dev=13.0.3.75=h0b38513_0
  - libnvptxcompiler-dev=13.1.115=0
  - libnvptxcompiler-dev_linux-64=13.1.115=0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpng=1.6.55=h421ea60_0
  - libsanitizer=15.2.0=h90f66d4_17
  - libsqlite=3.51.2=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-devel_linux-64=15.2.0=hd446a21_117
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libuuid=2.41.3=h5347b49_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxkbfile=1.1.0=h166bdaf_1
  - libxml2=2.15.1=h031cc0b_1
  - libxml2-16=2.15.1=hf2a90c1_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - nsight-compute=2025.4.1.2=h6f129cd_0
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pcre2=10.47=haa7fec5_0
  - pip=26.0.1=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.11.14=hd63d673_3_cpython
  - readline=8.3=h853b02a_0
  - setuptools=82.0.0=pyh332efcf_0
  - sysroot_linux-64=2.34=h3108a97_0
  - tk=8.6.13=noxft_h366c992_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.13=he1eb515_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.7=hb03c661_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.5=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - appdirs==1.4.4
      - astunparse==1.6.3
      - autograd==1.8.0
      - autoray==0.8.2
      - cachetools==7.0.1
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cudensitymat-cu12==0.4.0
      - cupauliprop-cu12==0.2.0
      - cuquantum-cu12==26.1.0
      - custabilizer-cu12==0.2.0
      - custatevec-cu12==1.12.0
      - cutensor-cu12==2.5.0
      - cutensornet-cu12==2.11.0
      - cycler==0.12.1
      - diastatic-malt==2.15.2
      - dill==0.4.1
      - fonttools==4.61.1
      - gast==0.7.0
      - idna==3.11
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.4.2
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nvjitlink-cu12==12.9.86
      - pennylane==0.44.0
      - pennylane-lightning==0.44.0
      - pillow==12.1.1
      - psutil==7.2.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - qiskit==1.4.5
      - qiskit-aer-gpu==0.15.1
      - qiskit-algorithms==0.4.0
      - requests==2.32.5
      - rustworkx==0.17.1
      - scipy==1.17.0
      - scipy-openblas32==0.3.31.22.1
      - six==1.17.0
      - stevedore==5.6.0
      - symengine==0.13.0
      - sympy==1.14.0
      - termcolor==3.3.0
      - tomlkit==0.14.0
      - typing-extensions==4.15.0
      - urllib3==2.6.3                                                                                                
